### ISSUE TITLE
translating the spliced sequences into the amino acid sequence

### ISSUE THREAD

**Issue by mictadlo** [tsaari88/FeatureSequence#15]
Hi,
Is there a way to enable translating the spliced sequences into the amino acid sequence?

Thank you in advance,

Michal

**Comment by twsaari** [comment]
Hi Michal, 
I'm afraid that this is outside of the scope of this particular plugin. I believe firmly in the "Each program does one thing well" tenet of linux/open source, rather than trying to be everything for everybody. As was mentioned on the GMOD/jbrowse thread, there are plenty of online tools which will convert DNA to amino acid sequence. It's also possible that there are other plugins which already serve this purpose, and if not, it'd be possible to implement. Closing this thread.

**Comment by nextgenusfs** [comment]
I'd second the request to have the translated amino acid sequence.  I'm not seeing anyway to do this -- which seems strange.  It would seem rather logical that users would want to click on a gene feature and access the translated amino acid sequence.  If the goal of FeatureSequence is to display sequence from features, the translated amino acid sequence is certainly within that scope.
